import Head from "next/head";
import dynamic from "next/dynamic";
import type { NextPage } from "next";
import Loader from "@/components/Loader";

const Print = dynamic(() => import("@/entities/Print"), {
  loading: () => <Loader />,
});

const PrintPage: NextPage = () => {
  return (
    <div className="grid h-full min-h-screen grid-cols-3 gap-4 bg-slate-200 p-4">
      <Head>
        <title>Salary tRPC | Print</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Print />
    </div>
  );
};

export default PrintPage;
